version: "3.7"
services:
  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./development/rabbitmq/volume/data/:/var/lib/rabbitmq/
      - ./development/rabbitmq/volume/log/:/var/log/rabbitmq/

  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "development"
      MONGO_INITDB_ROOT_PASSWORD: "development"
    ports:
      - "27017:27017"
    volumes:
      - ./development/mongodb/volume/data/:/data/db/
