name: Checkstyle

on:
  push:
    branches: [master]
    paths:
      - 'customer/**'
      - 'delivery/**'
      - 'order/**'
      - 'product/**'
      - 'review/**'
  pull_request:
    paths:
      - 'customer/**'
      - 'delivery/**'
      - 'order/**'
      - 'product/**'
      - 'review/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
